
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 5s
  # The batch processor combines multiple incoming telemetry data items into batches.
  # It waits up to 5 seconds before sending it further.
  
  attributes:
    actions:
      - key: landscape_token
        value: ${env:LANDSCAPE_TOKEN_ID}
        action: insert
      - key: token_secret
        value: ${env:LANDSCAPE_TOKEN_SECRET}
        action: insert
      - key: application_name
        value: "spring-petclinic-angular"
        action: insert
      - key: application_instance_id
        value: "0"
        action: insert
      - key: application_language
        value: "angular"
        action: insert
        

exporters:
  otlp:
    endpoint: "http://otel-collector:55678"      
    tls:
      insecure: true
  

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlp]